server:  
  port: ${PORT:8080}
  servlet:
    context-path: /jiwoo
  
spring:  
  application:
    name: jiwoo-admin
  datasource:
    url : jdbc:mysql://localhost:3306/jiwoo?useUnicode=yes&characterEncoding=UTF-8
    username : root
    password : 12345678
  jpa:
    hibernate:
      ddl-auto : update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  thymeleaf:
    cache : false