server:  
  port: ${PORT:8080}
  
spring:  
  application:
    name: jiwoo-admin
  datasource:
    url : jdbc:mysql://localhost:3306/jiwoo
    username : root
    password : 12345678
  jpa:
    hibernate:
      ddl-auto : update
    generate-ddl: true
    show-sql: true
  thymeleaf:
    cache : false